### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-orvlc4vu/poster

### ISSUE THREAD

**Issue by fereng** [flowroute/flowroute-numbers-python#1]
Is this module compatible with python3? Following the instruction, I got the following error when installing the module:

```
$ sudo pip3 install -r requirements.txt
Password:
The directory '/Users/kurucz/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
You are using pip version 7.0.1, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/Users/kurucz/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting Unirest==1.1.6 (from -r requirements.txt (line 1))
  Downloading Unirest-1.1.6.tar.gz
Collecting jsonpickle==0.7.1 (from -r requirements.txt (line 2))
  Downloading jsonpickle-0.7.1.tar.gz
Collecting poster==0.8.1 (from -r requirements.txt (line 3))
  Downloading poster-0.8.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-orvlc4vu/poster/setup.py", line 2, in <module>
        import poster
      File "/private/tmp/pip-build-orvlc4vu/poster/poster/__init__.py", line 29, in <module>
        import poster.streaminghttp
      File "/private/tmp/pip-build-orvlc4vu/poster/poster/streaminghttp.py", line 61
        print "send:", repr(value)
                    ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-orvlc4vu/poster
```

**Comment by bermudezmt** [comment]
Hi @fereng, this has been addressed via git commit: 5c444563925d6748f46c8cf5318f034ca65499ad

"The SDK supports only Python 2.x. Python 1.x and 3.x are not supported."
